version: '3.8'

services:
  pdf-benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-benchmark
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Berlin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Uncomment the following lines if you want to run in development mode
    # command: /bin/sh -c "while sleep 1000; do :; done"
    # entrypoint: /bin/bash
